package cfg

const LISTEN_ADDRESS string = "LISTEN_ADDRESS"
const STORAGE_ROOT string = "STORAGE_ROOT"
const STORAGE_LOGDIR string = "STORAGE_LOGDIR"
const ISOFT_IAAS_WEB string = "ISOFT_IAAS_WEB"
const ISOFT_DEPLOY_WEB string = "ISOFT_DEPLOY_WEB"
